### ISSUE TITLE
Add more data from well-engineered projects

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/NFBugs#17]
[This paper](https://link.springer.com/article/10.1007/s10664-017-9512-6) has a set of criteria for selecting well-engineered projects. It has its results posted [here](https://reporeapers.github.io/results/1.html). It has both python and Java repos. We talked about adding more data since right now, many of our issues are coming from smaller projects and I think this provides a good source of repos to use for our mining.

**Comment by aradu12** [comment]
added 44 new problems from 8 Java (17 reviewed) and 5 Python repos (10 reviewed)
