### ISSUE TITLE
Numbering off in Catacomb-Snatch?

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/NFBugs#28]
Catacomb-Snatch problems start at 2? [https://github.com/ualberta-smr/NFBugs/tree/master/java-data/Catacomb-Snatch/problems/api-related](https://github.com/ualberta-smr/NFBugs/tree/master/java-data/Catacomb-Snatch/problems/api-related)

**Comment by snadi** [comment]
Same for [https://github.com/ualberta-smr/NFBugs/tree/master/java-data/WaniKani-Ripoff-Project/problems/general-practise](https://github.com/ualberta-smr/NFBugs/tree/master/java-data/WaniKani-Ripoff-Project/problems/general-practise)

**Comment by aradu12** [comment]
due to deleting problems from the dataset. Will fix all the numbers once other issues are closed

**Comment by snadi** [comment]
Ok, we can revisit once you look at the other issues. Thanks!!
