### ISSUE TITLE
Is this really api-related?

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/NFBugs#29]
I'm not sure if [https://github.com/ualberta-smr/NFBugs/blob/master/java-data/EfficientAdapter/problems/api-related/1/problem.yml](https://github.com/ualberta-smr/NFBugs/blob/master/java-data/EfficientAdapter/problems/api-related/1/problem.yml) is an api-related problem. It seems more like this is a functionality they need: they need to be able to clear the cache when requested.

@aradu12  What do you think?

**Comment by aradu12** [comment]
I originally put it as api related because, though their function will be _used_ for their specific needs, under the surface it is implemented by just clearing a SparseArray, which is an android api (android.util.SparseArray). I was thinking future programmers using SparseArray might find it useful

**Comment by snadi** [comment]
I guess you can see it this way. The project-specific part is "on request" but the clearing aspect is related to clearing memory when using that API.

Ok, let's keep it as is then.
