### ISSUE TITLE
Security vs Encapsulation

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/NFBugs#33]
I don't think we can really classify this [https://github.com/ualberta-smr/NFBugs/blob/master/java-data/WaniKani-Ripoff-Project/problems/general-practise/2/problem.yml](https://github.com/ualberta-smr/NFBugs/blob/master/java-data/WaniKani-Ripoff-Project/problems/general-practise/2/problem.yml) as security. Using private members allows for better encapsulation and maintenance of the code, but is not really a security mechanism per se. In a sense, it can be seen as "internal data integrity" where another class cannot accidentally tamper with the internals of your data structures but it doesn't do anything for external security really. See [https://stackoverflow.com/questions/9201603/are-private-members-really-more-secure-in-java](https://stackoverflow.com/questions/9201603/are-private-members-really-more-secure-in-java) for a related discussion.

**Comment by aradu12** [comment]
Yeah that's a good discussion and good point! Do you think we should rename it to encapsulation or just delete this one altogether?

**Comment by snadi** [comment]
I would delete it altogether.
