### ISSUE TITLE
API-specific instead of general practise?

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/NFBugs#34]
Shouldn't [this](https://github.com/ualberta-smr/NFBugs/blob/master/java-data/cwac-wakeful/problems/general-practise/1/problem.yml) be  an API-related problem? I see that it is also a general practice, but in this specific example ,there is an API `PowerManager.WakeLock`, where when you call `acquire` to get a lock, you must call `release` even on exceptional paths, which is why it appears in the finally block

**Comment by aradu12** [comment]
will change this to api related
