### ISSUE TITLE
General practice vs API-related

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/NFBugs#35]
I don't think [this](https://github.com/ualberta-smr/NFBugs/blob/master/java-data/deltachat-android/problems/api-related/1/problem.yml) is api related. Saying that you should replace a HashMap with a String is misleading. Here, I think the issue was that they unnecessarily stored things in a map, while they only need a single unique string at a time. I would say either a general practice message can be deduced from this or we can remove it altogether.

@aradu12 What do you think?

**Comment by aradu12** [comment]
yep, this is kind of a unique issue the programmers had. I would say the general practise advice may not be valuable in the long run, since it basically boils down to "don't make things more complex than they need to be" lol. Maybe removing it altogether is best

**Comment by snadi** [comment]
Ok, let's remove it then.
