### ISSUE TITLE
Possible inaccurate description? 

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/NFBugs#49]
[https://github.com/ualberta-smr/NFBugs/blob/master/py-data/Theano/problems/api-related/2/problem.yml](https://github.com/ualberta-smr/NFBugs/blob/master/py-data/Theano/problems/api-related/2/problem.yml) .. Isn't this about using memset to clear an array rather than individually set each element  to 0?

**Comment by aradu12** [comment]
I believe memset clears an array BY individually setting each element to 0, does it not? 

See: 
https://docs.python.org/3.6/library/ctypes.html 
and
https://www.tutorialspoint.com/c_standard_library/c_function_memset.htm

**Comment by snadi** [comment]
Yeah, that's right but I guess the description "(de)allocate memory faster using ctypes library" confused me. Can you perhaps change it to "using ctypes.memset" .. It is also not about deallocating memory but rather about clearing (to 0) or initialization. It doesn't deallocate the memory.
