### ISSUE TITLE
ExampleProject is not a good target project

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/NFBugs#6]
How did you come across the [ExampleProject](https://github.com/MidasChallenge2018/ExampleProject) repo based on the used methodology? It has no stars or forks, is written in Chinese, and seems like some example from the title (so not a “real” project). I think we should remove it from the data set.

**Comment by aradu12** [comment]
We decided to include these projects so that researchers can choose to analyze problems faced by novice programmers. Users can filter the dataset by number of stars to exclude these projects.
